services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learn-jenkins-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - docker

  docker:
    image: docker:24-dind
    container_name: docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "2375:2375"
    command: --host=tcp://0.0.0.0:2375
    volumes:
      - docker_data:/var/lib/docker

volumes:
  jenkins_home:
  docker_data:
